location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/uvdar_leader_follower.git
    name: uvdar_leader_follower
    rev: system_1.5
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_leader_follower
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/summer_school_supervisor.git
    name: summer_school_supervisor
    rev: system_1.5
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/summer_school_supervisor
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/uvdar_leader_follower.git
    name: uvdar_leader_follower
    rev: 67418a881b4b744618a468841df7a7c75bf094a4
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_leader_follower
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/summer_school_supervisor.git
    name: summer_school_supervisor
    rev: 3f3b7cf8526c796d736ae02b5fb74639ecd7d148
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/summer_school_supervisor
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
