location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/uvdar_leader_follower.git
    name: uvdar_leader_follower
    rev: system_1.5
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_leader_follower
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/summer_school_supervisor.git
    name: summer_school_supervisor
    rev: system_1.5
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/summer_school_supervisor
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/uvdar_leader_follower.git
    name: uvdar_leader_follower
    rev: 8814bc552cf3e97a6636679d68e209029c2f7f8f
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_leader_follower
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/summer_school_supervisor.git
    name: summer_school_supervisor
    rev: befba01209b857189c1416e16b82ee76af3cbacb
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/summer_school_supervisor
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
