location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_serial.git
    name: mrs_serial
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_serial
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/uvdar_leader_follower.git
    name: uvdar_leader_follower
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_leader_follower
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/uvdar_core.git
    name: uvdar_core
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_core
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/uvdar_gazebo_plugin.git
    name: uvdar_gazebo_plugin
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_gazebo_plugin
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/summer_school_supervisor.git
    name: summer_school_supervisor
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/summer_school_supervisor
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/trajectory_loader.git
    name: trajectory_loader
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/trajectory_loader
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_serial.git
    name: mrs_serial
    rev: b3b1cf8d392b32c6fe05dd9c6609738e4cfe4294
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_serial
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/uvdar_leader_follower.git
    name: uvdar_leader_follower
    rev: eada51534279ecc5c5d72ac93341fea56f57401f
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_leader_follower
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/uvdar_core.git
    name: uvdar_core
    rev: 63a984bfb48798a6f8fb09bd5a3df322467085e3
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_core
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/uvdar_gazebo_plugin.git
    name: uvdar_gazebo_plugin
    rev: a1546bf67d5c075844e81173518e058cd48185d3
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_gazebo_plugin
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/summer_school_supervisor.git
    name: summer_school_supervisor
    rev: e4660dba6eb4333d8779f237051b669701c25b09
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/summer_school_supervisor
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/trajectory_loader.git
    name: trajectory_loader
    rev: 719b1600f56e2d2d8cf0290c5ec03a0f56d6bd7c
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/trajectory_loader
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
