location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/uvdar_leader_follower.git
    name: uvdar_leader_follower
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_leader_follower
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/uvdar_core.git
    name: uvdar_core
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_core
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/uvdar_gazebo_plugin.git
    name: uvdar_gazebo_plugin
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_gazebo_plugin
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/summer_school_supervisor.git
    name: summer_school_supervisor
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/summer_school_supervisor
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/uvdar_leader_follower.git
    name: uvdar_leader_follower
    rev: d3220d8896dfbcae77b617081810cc5356a5d15b
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_leader_follower
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/uvdar_core.git
    name: uvdar_core
    rev: 8cfc1b252256280f55af2ac8709198a094881162
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_core
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/uvdar_gazebo_plugin.git
    name: uvdar_gazebo_plugin
    rev: 9af88cae229b85e98dfbb87289186df3072310f0
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_gazebo_plugin
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/summer_school_supervisor.git
    name: summer_school_supervisor
    rev: 98c9528593fa34f3afa076b9afc0dab4f9842363
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/summer_school_supervisor
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
