location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/uvdar_leader_follower.git
    name: uvdar_leader_follower
    rev: system_1.5
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_leader_follower
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/summer_school_supervisor.git
    name: summer_school_supervisor
    rev: system_1.5
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/summer_school_supervisor
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/uvdar_leader_follower.git
    name: uvdar_leader_follower
    rev: 2bae9ebc19ff09a937b07451bf9397119dc486c7
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/uvdar_leader_follower
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/summer_school_supervisor.git
    name: summer_school_supervisor
    rev: f5fe0ad902911d238c48f8c997b7dae483196944
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/summer_school_supervisor
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
