mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      "gps_garmin"
    ]

    initial_state_estimator: "gps_garmin" # will be used as the first state estimator
    agl_height_estimator: "garmin_agl" # only slightly filtered height for checking min height (not used in control feedback)

  uav_manager:

    takeoff:

      during_takeoff:
        controller: "MpcController"
        tracker: "LandoffTracker"

      after_takeoff:
        controller: "MpcController" # more robust
        # controller: "Se3Controller" # more precise
        tracker: "MpcTracker"

  constraint_manager:

    medium:

      horizontal:
        speed: 5.0
        acceleration: 1.0
        jerk: 20.0
        snap: 20.0

      vertical:

        ascending:
          speed: 3.0
          acceleration: 2.0
          jerk: 20.0
          snap: 20.0

        descending:
          speed: 2.0
          acceleration: 1.0
          jerk: 20.0
          snap: 20.0

      heading:
        speed: 5.0
        acceleration: 1.0
        jerk: 10.0
        snap: 10.0

      angular_speed:
        roll: 60.0
        pitch: 60.0
        yaw: 60.0

      tilt: 60.0 # [deg]


    estimator_types: [
      "gps_garmin",
      # "rtk"
    ]

    allowed_constraints:
      gps_garmin: ["slow", "medium", "fast"]
      # rtk: ["slow", "medium", "fast"]

    default_constraints:
      gps_garmin: "medium"
      # rtk: "medium"

mrs_uav_trackers:

  mpc_tracker:

    wiggle:
      enabled: false
      amplitude: 0.5 # [m]
      frequency: 0.2 # [Hz]

    # mrs collision avoidance
    collision_avoidance:

      enabled:           true # disabling this will stop this UAV to react to others, but it will still transmit data to others
      enabled_passively: true # disabling this will stop this uav to even transmit its data to others (only if enabled: false)
      radius: 1.0 # [m]
      correction: 1.0 # [m]
